export const GET_CATEGORY = "GET_CATEGORY";
// export const GET_CATEGORIES = "GET_CATEGORIES";
export const PUT_CATEGORY = "PUT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const POST_CATEGORY = "POST_CATEGORY";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS"; 
export const PUT_PRODUCT = "PUT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const POST_PRODUCT = "POST_PRODUCT";
